
run:
  project: 'AST-multi-label'
  name: 'timbresearch_bs24'

dataset:
  use_small_dataset:
    train: True
    valid: True
    test: False
  id2label:  # None: will be set automatically when loading a dataset

model:
  base: 'AST'
  type: 'MultiLabelClassification'
  pretrained: "MIT/ast-finetuned-audioset-12-12-0.447"
  sr: 16000
  num_mel_bins: 128
  max_num_mel_frames: 1024

training:
  batch_size: 24
  start_lr: 0.0001  # lr 0.00015 for bs 48
  end_lr: 0.00001
  num_steps: 4000  # 2000 for bs 48
  device: 'cuda:0'
  criterion: "BCE"

validation:
  period_in_steps: 400
  valid_first_step: False
